"""Add peer_cluster_id column

Revision ID: 306e33531f2c
Revises: 34eccf3c7600
Create Date: 2025-10-28 13:42:44.855733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '306e33531f2c'
down_revision = '34eccf3c7600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fact_company_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peer_cluster_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_fact_company_summary_peer_cluster_id'), ['peer_cluster_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fact_company_summary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fact_company_summary_peer_cluster_id'))
        batch_op.drop_column('peer_cluster_id')

    # ### end Alembic commands ###
