"""Add new columns to FactCompanySummary and add new tables

Revision ID: 34eccf3c7600
Revises: e6123b889703
Create Date: 2025-10-26 18:47:51.725537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34eccf3c7600'
down_revision = 'e6123b889703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_financial_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('statement_type', sa.String(length=20), nullable=False),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['dim_company.ticker'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'report_date', 'statement_type', 'metric_name', name='_ticker_date_statement_metric_uc')
    )
    with op.batch_alter_table('fact_financial_statements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fact_financial_statements_report_date'), ['report_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_financial_statements_statement_type'), ['statement_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_financial_statements_ticker'), ['ticker'], unique=False)

    op.create_table('fact_news_sentiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('article_url', sa.String(length=1000), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sentiment_label', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['dim_company.ticker'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_url')
    )
    with op.batch_alter_table('fact_news_sentiment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fact_news_sentiment_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_news_sentiment_ticker'), ['ticker'], unique=False)

    with op.batch_alter_table('fact_company_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ebitda_margin', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('trailing_eps', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('forward_pe', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('analyst_target_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('long_business_summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fact_company_summary', schema=None) as batch_op:
        batch_op.drop_column('long_business_summary')
        batch_op.drop_column('analyst_target_price')
        batch_op.drop_column('forward_pe')
        batch_op.drop_column('trailing_eps')
        batch_op.drop_column('ebitda_margin')

    with op.batch_alter_table('fact_news_sentiment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fact_news_sentiment_ticker'))
        batch_op.drop_index(batch_op.f('ix_fact_news_sentiment_published_at'))

    op.drop_table('fact_news_sentiment')
    with op.batch_alter_table('fact_financial_statements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fact_financial_statements_ticker'))
        batch_op.drop_index(batch_op.f('ix_fact_financial_statements_statement_type'))
        batch_op.drop_index(batch_op.f('ix_fact_financial_statements_report_date'))

    op.drop_table('fact_financial_statements')
    # ### end Alembic commands ###
