"""Add fcf_ttm and revenue_ttm to FactCompanySummary

Revision ID: 5d687f2f1a7e
Revises: 306e33531f2c
Create Date: 2025-10-28 15:14:03.058027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d687f2f1a7e'
down_revision = '306e33531f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fact_company_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fcf_ttm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('revenue_ttm', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fact_company_summary', schema=None) as batch_op:
        batch_op.drop_column('revenue_ttm')
        batch_op.drop_column('fcf_ttm')

    # ### end Alembic commands ###
