"""Initial migration for all tables

Revision ID: 8cd416735e5b
Revises: 
Create Date: 2025-10-24 21:07:29.177498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd416735e5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_assumptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('forecast_years', sa.Integer(), nullable=True),
    sa.Column('eps_growth', sa.Float(), nullable=True),
    sa.Column('terminal_pe', sa.Float(), nullable=True),
    sa.Column('dcf_simulations', sa.Integer(), nullable=True),
    sa.Column('dcf_growth_min', sa.Float(), nullable=True),
    sa.Column('dcf_growth_mode', sa.Float(), nullable=True),
    sa.Column('dcf_growth_max', sa.Float(), nullable=True),
    sa.Column('dcf_perpetual_min', sa.Float(), nullable=True),
    sa.Column('dcf_perpetual_mode', sa.Float(), nullable=True),
    sa.Column('dcf_perpetual_max', sa.Float(), nullable=True),
    sa.Column('dcf_wacc_min', sa.Float(), nullable=True),
    sa.Column('dcf_wacc_mode', sa.Float(), nullable=True),
    sa.Column('dcf_wacc_max', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_selection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol_type', sa.String(length=10), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_selection')
    op.drop_table('user_assumptions')
    op.drop_table('user')
    # ### end Alembic commands ###
