"""Add credit_rating to dim_company

Revision ID: a1e48c0f0128
Revises: 5d687f2f1a7e
Create Date: 2025-10-30 14:36:50.616093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1e48c0f0128'
down_revision = '5d687f2f1a7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dim_company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_rating', sa.String(length=32), nullable=True))

    with op.batch_alter_table('fact_company_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_rating', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fact_company_summary', schema=None) as batch_op:
        batch_op.drop_column('credit_rating')

    with op.batch_alter_table('dim_company', schema=None) as batch_op:
        batch_op.drop_column('credit_rating')

    # ### end Alembic commands ###
