"""Add analytics tables for warehouse

Revision ID: e6123b889703
Revises: 8cd416735e5b
Create Date: 2025-10-26 12:01:22.474719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6123b889703'
down_revision = '8cd416735e5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_company',
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('fact_company_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('date_updated', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('beta', sa.Float(), nullable=True),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('pb_ratio', sa.Float(), nullable=True),
    sa.Column('ev_ebitda', sa.Float(), nullable=True),
    sa.Column('revenue_growth_yoy', sa.Float(), nullable=True),
    sa.Column('revenue_cagr_3y', sa.Float(), nullable=True),
    sa.Column('net_income_growth_yoy', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('de_ratio', sa.Float(), nullable=True),
    sa.Column('operating_margin', sa.Float(), nullable=True),
    sa.Column('cash_conversion', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['dim_company.ticker'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date_updated', name='_ticker_date_uc')
    )
    with op.batch_alter_table('fact_company_summary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fact_company_summary_date_updated'), ['date_updated'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_company_summary_ticker'), ['ticker'], unique=False)

    op.create_table('fact_daily_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['dim_company.ticker'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', name='_ticker_price_date_uc')
    )
    with op.batch_alter_table('fact_daily_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fact_daily_prices_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_daily_prices_ticker'), ['ticker'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fact_daily_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fact_daily_prices_ticker'))
        batch_op.drop_index(batch_op.f('ix_fact_daily_prices_date'))

    op.drop_table('fact_daily_prices')
    with op.batch_alter_table('fact_company_summary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fact_company_summary_ticker'))
        batch_op.drop_index(batch_op.f('ix_fact_company_summary_date_updated'))

    op.drop_table('fact_company_summary')
    op.drop_table('dim_company')
    # ### end Alembic commands ###
